name: Feature Request
description: Suggest a new feature for the AI Therapeutic Questionnaire
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the system would this feature affect?
      options:
        - Backend (Python/FastAPI)
        - Mobile App (Flutter)
        - AI Question Generation
        - Question Configuration
        - Documentation
        - New Component
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem or need this feature would address...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: Describe any alternative solutions you've considered...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my usage

  - type: textarea
    id: therapeutic-impact
    attributes:
      label: Therapeutic Impact
      description: How would this feature improve the therapeutic value of the questionnaire?
      placeholder: Describe how this would help users with their self-reflection journey...

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to help implement this feature
        - label: I can provide testing and feedback
        - label: I can help with documentation

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
